server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: false
      local: false

    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    soundcloudFilterOutPreviewTracks: false

    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clientOptions:
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      TVHTML5_SIMPLY:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      ANDROID:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: false
      WEBEMBEDDED:
        playback: false
        playlistLoading: false
        searching: false
        videoLoading: false
    clients:
      - MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID
      - IOS
      - TV
      - TVHTML5_SIMPLY

    remoteCipher:
      url: "https://cipher.kikkia.dev/"

    oauth:
      enabled: true
      refreshToken: "your_token_here"
      skipInitialization: false

    proxy:
      host: "127.0.0.1"
      port: 40000

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO

http:
  proxy:
    host: "127.0.0.1"
    port: 40000
    username: ""
    password: ""
